### ISSUE TITLE
DiscordAPIError: Unknown interaction (code: 10062, httpStatus: 404)

### ISSUE THREAD

**Issue by TravisMalveda** [giorgi-o/SkinPeek#10]
![Untitled design](https://user-images.githubusercontent.com/80034955/154388241-d2f61849-14a8-4012-94e9-de850eaaa6d9.png)
Getting this error when using /shop, /balance, etc.
Started happening yesterday.

**Comment by TravisMalveda** [comment]
Issue is gone now @.@

**Comment by giorgi-o** [comment]
This usually means you have the bot running in two places at once btw
