### ISSUE TITLE
checkAlerts

### ISSUE THREAD

**Issue by sugoides** [giorgi-o/SkinPeek#23]
![image](https://user-images.githubusercontent.com/73387545/161169537-8be55f2f-afe6-4c66-b2eb-a588f0f73fd3.png)

Only the first 4 users are getting checked for offers, while I have 6 users registered on the bot

**Comment by warriorzz** [comment]
Are you sure that everyone added at least one alert?

**Comment by sugoides** [comment]
> Are you sure that everyone added at least one alert?

owww yeah the only ones that get checked are the ones with alerts,

My bad, Ill close the issue
