### ISSUE TITLE
Having a hard time understanding what to put in /cookie option

### ISSUE THREAD

**Issue by brycemck** [giorgi-o/SkinPeek#32]
What do you copy from the riot games auth cookie into the command in the discord bot?

Thanks!

**Comment by MavenDisrrpt** [comment]
This is assuming you have found auth.riotgames.com in your network tab and have found the cookie in the request header section and see a bunch of random characters. Go ahead and copy that entire thing (except for cookie: of course). At least with chrome, haven't tried other browsers, you can just right click on cookie and it will give you an option to "Copy Value". Just paste that whole thing in when you provide the cookie to the discord bot.

**Comment by giorgi-o** [comment]
Yeah, basically everything in [this image](https://user-images.githubusercontent.com/20621396/134550706-76d1b5a0-ed45-454f-9f4c-e0740a4c6a27.png) that is censored, from `did=` till the end. I didn't know about right clicking > copy value, it's a nice shortcut @MavenDisrrpt!

@brycemck Let me know if you still have issues using `/cookies`.

**Comment by brycemck** [comment]
That clears it up, thank you! Really appreciate it.
