### ISSUE TITLE
shop statistic

### ISSUE THREAD

**Issue by sugoides** [giorgi-o/SkinPeek#34]
what does the shop stats do?
can u put screenshot on README about this?

**Comment by giorgi-o** [comment]
I just released the `/stats` command in https://github.com/giorgi-o/SkinPeek/commit/9e389b89c3d0c872053c73f07cb447d740e0b112, check it out!

**Comment by sugoides** [comment]
> I just released the `/stats` command in [9e389b8](https://github.com/giorgi-o/SkinPeek/commit/9e389b89c3d0c872053c73f07cb447d740e0b112), check it out!

I mean would be able to send screenshot of it, 'cuz i'll be going to update my mod on ur repo if I pulled this repo

**Comment by giorgi-o** [comment]
There's a screenshot of it in the readme. Here's another one for individual skins:
![image](https://user-images.githubusercontent.com/20621396/165753804-d86cbaef-a76a-4614-8782-775da41ad0b8.png)
