### ISSUE TITLE
is this from the issue, being the valorant servers are down?

### ISSUE THREAD

**Issue by sugoides** [giorgi-o/SkinPeek#43]
![image](https://user-images.githubusercontent.com/73387545/174741652-e8ddae4c-a95c-43a0-906d-11ecad91b034.png)

**Comment by Kyedae** [comment]
yeah, cloudflare affected multiple services.

**Comment by sugoides** [comment]
> yeah, cloudflare affected multiple services.

ohhh okay thanks
