### ISSUE TITLE
Sometimes coudn't fetch shop

### ISSUE THREAD

**Issue by sugoides** [giorgi-o/SkinPeek#54]
![image](https://user-images.githubusercontent.com/73387545/196150336-0390a014-2074-4ce5-b98c-f397cafedb2a.png)
![image](https://user-images.githubusercontent.com/73387545/196150394-e92c0f70-d634-45a8-b1f3-908bcdac95b4.png)

**Comment by giorgi-o** [comment]
Does this still happen? No one else has reported this issue.

Also I think you mentionned you are using a modified version of the bot. Can you reproduce it on the base version?
