### ISSUE TITLE
"emoji limit reached" even though its not

### ISSUE THREAD

**Issue by iwa** [giorgi-o/SkinPeek#63]
hello,

really good bot so far! i love the configurability and reliability of the bot
but one issue i'm having so far is that emotes wont upload on my server

- skinpeek is running through docker
- bot has been setup in guild-mode only
- when i invited the bot, the guild was full of emotes, then i cleaned up my emotes and i now have 20 slots available on 100
- even after restarts, it still says i've maxed my emoji slots

![Screenshot 2022-11-18 at 14 13 52](https://user-images.githubusercontent.com/19956672/202713376-b09d53e6-d5b8-4173-9314-73be124a756a.png)
<img width="628" alt="Screenshot 2022-11-18 at 14 22 21" src="https://user-images.githubusercontent.com/19956672/202714875-8b557098-fab4-4196-9ff2-9b3b9a6ce0d9.png">

could you help me pls ? :/

**Comment by giorgi-o** [comment]
Does this still happen a few hours later? Sometimes Discord can be slow with their emoji cache

**Comment by iwa** [comment]
yup, still happening today :/

**Comment by giorgi-o** [comment]
Fixed in #65
