### ISSUE TITLE
localiseSkinNames option in config.json does nothing

### ISSUE THREAD

**Issue by ngnducnhat** [giorgi-o/SkinPeek#74]
localiseSkinNames

i ready change this value to false but in my embed message still is not english name of skin fix it pls or teach me fix it
![image](https://user-images.githubusercontent.com/69428695/213545283-bd6bb809-eaad-4108-91cf-a9f5242c17a7.png)

**Comment by giorgi-o** [comment]
Looks like I forgot to implement that option when I was refactoring the language code, whoops. I'll fix it in the next update.

In the meantime, you can do `/settings set language` and choose english :)
