### ISSUE TITLE
 Default skin 0 VP shop

### ISSUE THREAD

**Issue by bur4kcoders** [giorgi-o/SkinPeek#78]
Bot crashes in shop event on first login
![2](https://user-images.githubusercontent.com/85685192/229261465-e328a34a-698d-4682-91c8-5bd88ad21e5f.png)

**Comment by TNTcraftHIM** [comment]
Same here
![image](https://user-images.githubusercontent.com/35992542/229269248-0e12d53b-2494-4522-870b-0f8662cc00b2.png)

**Comment by giorgi-o** [comment]
Happy April fools 😜

**Comment by giorgi-o** [comment]
It will magically fix itself on April 2, midnight UTC :)

If you *really* want it fixed now, just change your system time to any other date than April 1st.
