### ISSUE TITLE
unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by eznxxy** [giorgi-o/SkinPeek#93]
when im trying to use /login command, im facing this error
any recommendation how to fix it?

OS: Windows 10 Home Single Language v22H2
Nodejs: 16.19.0

>  Riot didn't return any cookies during the auth request! Cloudflare might have something to do with it...
 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at redeemUsernamePassword (file:///C:/Users/Velociraptor/Downloads/Compressed/SkinPeek-master/valorant/auth.js:162:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async queueUsernamePasswordLogin (file:///C:/Users/Velociraptor/Downloads/Compressed/SkinPeek-master/valorant/authQueue.js:33:38)
    at async loginUsernamePassword (file:///C:/Users/Velociraptor/Downloads/Compressed/SkinPeek-master/discord/authManager.js:40:17)
    at async Client.<anonymous> (file:///C:/Users/Velociraptor/Downloads/Compressed/SkinPeek-master/discord/bot.js:910:21)

**Comment by eznxxy** [comment]
Ahh i see that's make sense.

Well this is my first time create a discord bot so im just install it on my own machine, and for now as you mentioned above i will try to self-hosting the bot.

Anyway thank you, your explanation is nice.

**Comment by tylernguyen** [comment]
I'm running into this issue self-hosting the bot. I have 4 users.

**Comment by giorgi-o** [comment]
Completely forgot to mention it here (sorry!) but commit 70b485560b4dcf8a5f0221afa9476b6ffd0ecfe4 seems to have fixed it, at least for now. If anyone still gets an error after updating, please let me know.

**Comment by eznxxy** [comment]
Yepp its work for me, thanks

**Comment by jorin21** [comment]
Hey I'm still getting this error. I tried running it on a cloud server and found this thread but now I'm trying to run it from my home machine and it is giving the same error.

**Comment by ConnorDoesDev** [comment]
> Hey I'm still getting this error. I tried running it on a cloud server and found this thread but now I'm trying to run it from my home machine and it is giving the same error.

wrong issue gang
riot recently (a while ago actually) implemented a new auth system that pretty much "requires" you to use a captcha solver or just have users grab their cookies and log in with them

**Comment by jorin21** [comment]
Oh my fault then that makes sense. Sucks riot did that. Time to just grab my own cookies then. Preciate it!

**Comment by ConnorDoesDev** [comment]
> Oh my fault then that makes sense. Sucks riot did that. Time to just grab my own cookies then. Preciate it!

i'll copy paste the guide i wrote for my users for you:
little english guide on how to get your cookie, for the non-brazilian users :)
# Acquiring your cookie
1. go [here](https://account.riotgames.com/) and login
2. open developer tools using ctrl + shift + i (or right click->inspect element)
3. click on network
4. with the devtools menu still open, go to https://auth.riotgames.com/ (do NOT open a new tab!! stay in the same tab you used to log into the first page)a
5. lotta stuff should pop up, click on the row that says "auth.riotgames.com"
6. scroll down till you see "REQUEST Headers"
7. click on it and scroll till you see an entry named "Cookie:"
8. copy the entire entry value
# Troubleshooting
- check if you copied the correct entry and make sure you **ONLY copied the value**, not the Cookie: part
- make sure you copied the cookie that was in **Request Headers**, not Response Headers

**Comment by jorin21** [comment]
> > Oh my fault then that makes sense. Sucks riot did that. Time to just grab my own cookies then. Preciate it!
> 
> i'll copy paste the guide i wrote for my users for you:
> 
> little english guide on how to get your cookie, for the non-brazilian users :)
> 
> # Acquiring your cookie
> 1. go [here](https://account.riotgames.com/) and login
> 2. open developer tools using ctrl + shift + i (or right click->inspect element)
> 3. click on network
> 4. with the devtools menu still open, go to https://auth.riotgames.com/ (do NOT open a new tab!! stay in the same tab you used to log into the first page)a
> 5. lotta stuff should pop up, click on the row that says "auth.riotgames.com"
> 6. scroll down till you see "REQUEST Headers"
> 7. click on it and scroll till you see an entry named "Cookie:"
> 8. copy the entire entry value
> 
> # Troubleshooting
> * check if you copied the correct entry and make sure you **ONLY copied the value**, not the Cookie: part
> * make sure you copied the cookie that was in **Request Headers**, not Response Headers

Thank you!
